import crypto from 'node:crypto';

const META_GRAPH_VERSION = 'v21.0';

/* Meta requires PII to be normalised then SHA-256 hashed before it leaves our server. */
const sha256 = v => crypto.createHash('sha256').update(v).digest('hex');
const hashed = v => {
  const s = String(v ?? '').trim().toLowerCase();
  return s ? sha256(s) : null;
};
/* SG mobiles arrive as 8 digits (or with a +65 / 65 prefix); Meta matches on country code + number. */
const hashedPhone = raw => {
  const digits = String(raw ?? '').replace(/\D/g, '');
  if (!digits) return null;
  return sha256(digits.length === 8 ? `65${digits}` : digits);
};

async function sendMetaConversion(body, req) {
  const token = process.env.META_CAPI_TOKEN;
  const datasetId = process.env.META_DATASET_ID;
  if (!token || !datasetId) return { skipped: 'not configured' };

  const [firstName, ...restName] = String(body.name ?? '').trim().split(/\s+/);
  const forwarded = req.headers['x-forwarded-for'];
  const clientIp = (Array.isArray(forwarded) ? forwarded[0] : forwarded || '').split(',')[0].trim();

  // event_id is generated by the quiz and sent to the pixel too, so Meta dedupes the pair.
  const userData = {
    em: hashed(body.email),
    ph: hashedPhone(body.phone),
    fn: hashed(firstName),
    ln: restName.length ? hashed(restName.join(' ')) : null,
    country: sha256('sg'),
    client_ip_address: clientIp || undefined,
    client_user_agent: req.headers['user-agent'] || undefined,
    fbp: body.fbp || undefined,
    fbc: body.fbc || undefined
  };
  for (const k of Object.keys(userData)) if (!userData[k]) delete userData[k];

  const payload = {
    data: [{
      event_name: 'Lead',
      event_time: Math.floor(Date.now() / 1000),
      event_id: body.event_id,
      event_source_url: body.page_url || 'https://www.alsonmah.com/quiz/',
      action_source: 'website',
      user_data: userData,
      custom_data: { content_name: 'Property Retirement Score', band: body.band, score: body.score }
    }]
  };

  const res = await fetch(
    `https://graph.facebook.com/${META_GRAPH_VERSION}/${datasetId}/events?access_token=${encodeURIComponent(token)}`,
    { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }
  );
  const result = await res.json().catch(() => ({}));
  if (!res.ok) console.error('Meta CAPI error:', res.status, JSON.stringify(result));
  else console.log('Meta CAPI ok:', JSON.stringify(result));
  return result;
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const webhookUrl = process.env.QUIZ_ZAPIER_WEBHOOK_URL;
  if (!webhookUrl) {
    console.error('QUIZ_ZAPIER_WEBHOOK_URL environment variable not set');
    return res.status(500).json({ error: 'Webhook not configured' });
  }

  try {
    const body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;

    // CRM relay and Meta CAPI are independent: neither failure may block the other or the visitor.
    const [zapier] = await Promise.allSettled([
      fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      }),
      sendMetaConversion(body, req).catch(err => console.error('Meta CAPI failed:', err))
    ]);

    if (zapier.status === 'fulfilled') console.log('Quiz Zapier webhook response:', zapier.value.status);
    else console.error('Quiz Zapier webhook error:', zapier.reason);

    return res.status(200).json({ success: true });
  } catch (error) {
    console.error('Quiz webhook error:', error);
    return res.status(500).json({ error: 'Failed to send webhook' });
  }
}
